//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Caching
{
    using System;
    using System.Runtime.Caching;


    public sealed class ClassCache209758666 : CM.Caching.Examples.ISource
    {

        private System.Runtime.Caching.MemoryCache cache;

        private CM.Caching.Examples.ISource instance;

        private System.Func<System.Runtime.Caching.CacheItemPolicy> createCacheItemPolicy;

        public ClassCache209758666(CM.Caching.Examples.ISource instance, string cacheName, System.Func<System.Runtime.Caching.CacheItemPolicy> createCacheItemPolicy)
        {
            this.instance = instance;
            this.createCacheItemPolicy = createCacheItemPolicy;
            this.cache = new System.Runtime.Caching.MemoryCache(cacheName);
        }

        public string MainMethod(string myParameter)
        {
            string g() { return someMethod(myParameter); }
            return someOtherMethod(g);
        }

        public System.Nullable<int> GetSomeMoreData(System.Nullable<int> myParameter1, System.Nullable<bool> optionalParameter)
        {
            string cacheKey;
            cacheKey = CM.Caching.ClassCache.MethodCallToKey("GetSomeMoreData", myParameter1, optionalParameter);
            return CM.Caching.ClassCache.GetFromCache<System.Nullable<int>>(cache, cacheKey, instance.GetSomeMoreData(myParameter1, optionalParameter), createCacheItemPolicy);
        }

        public System.Threading.Tasks.Task<CM.Caching.Examples.SourceObject> GetDataAsync(string myParameter)
        {
            string cacheKey;
            cacheKey = CM.Caching.ClassCache.MethodCallToKey("GetDataAsync", myParameter);
            return System.Threading.Tasks.Task.FromResult(default(CM.Caching.Examples.SourceObject));
        }
    }
}